In [1]:
#Loan status predication python with Machine Learning

In [2]:
import numpy as num
import pandas as pd

In [3]:
data =pd.read_csv("LoanApprovalPrediction.csv")
  



In [4]:
data

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  Loan              Amount  \
0               5849                0.0                       NaN   
1               4583             1508.0                     128.0   
2               3000                0.0                      66.0   
3               2583             2358.0                     120.0   
4               6000                0.0                     141.0   
..               ...                ...                       ...   
609             2900                0.0                      71.0   
610             4106                0.0                      40.0   
611             8072              240.0                     253.0   
612             7583                0.0                     187.0   
613             4583                0.0                     133.0   

     Loan_Amount_Term  Credit_History Property_Area Loan_Status  
0               360.0             1.0         Urban           Y  
1               360.0             1.0         Rural           N  
2               360.0             1.0         Urban           Y  
3               360.0             1.0         Urban           Y  
4               360.0             1.0         Urban           Y  
..                ...             ...           ...         ...  
609             360.0             1.0         Rural           Y  
610             180.0             1.0         Rural           Y  
611             360.0             1.0         Urban           Y  
612             360.0             1.0         Urban           Y  
613             360.0             0.0     Semiurban           N  

[614 rows x 13 columns]

In [5]:
data.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  Loan              Amount  \
0             5849                0.0                       NaN   
1             4583             1508.0                     128.0   
2             3000                0.0                      66.0   
3             2583             2358.0                     120.0   
4             6000                0.0                     141.0   

   Loan_Amount_Term  Credit_History Property_Area Loan_Status  
0             360.0             1.0         Urban           Y  
1             360.0             1.0         Rural           N  
2             360.0             1.0         Urban           Y  
3             360.0             1.0         Urban           Y  
4             360.0             1.0         Urban           Y

In [6]:
data.head(10)

Loan_ID       Gender Married Dependents     Education Self_Employed  \
0  LP001002         Male      No          0      Graduate            No   
1  LP001003         Male     Yes          1      Graduate            No   
2  LP001005         Male     Yes          0      Graduate           Yes   
3  LP001006         Male     Yes          0  Not Graduate            No   
4  LP001008         Male      No          0      Graduate            No   
5  LP001011  Transgender     Yes          2      Graduate           Yes   
6  LP001013         Male     Yes          0  Not Graduate            No   
7  LP001014         Male     Yes         3+      Graduate            No   
8  LP001018         Male     Yes          2      Graduate            No   
9  LP001020         Male     Yes          1      Graduate            No   

   ApplicantIncome  CoapplicantIncome  Loan              Amount  \
0             5849                0.0                       NaN   
1             4583             1508.0                     128.0   
2             3000                0.0                      66.0   
3             2583             2358.0                     120.0   
4             6000                0.0                     141.0   
5             5417             4196.0                     267.0   
6             2333             1516.0                      95.0   
7             3036             2504.0                     158.0   
8             4006             1526.0                     168.0   
9            12841            10968.0                     349.0   

   Loan_Amount_Term  Credit_History Property_Area Loan_Status  
0             360.0             1.0         Urban           Y  
1             360.0             1.0         Rural           N  
2             360.0             1.0         Urban           Y  
3             360.0             1.0         Urban           Y  
4             360.0             1.0         Urban           Y  
5             360.0             1.0         Urban           Y  
6             360.0             1.0         Urban           Y  
7             360.0             0.0     Semiurban           N  
8             360.0             1.0         Urban           Y  
9             360.0             1.0     Semiurban           N

In [7]:
data = pd.read_csv("LoanApprovalPrediction.csv")
data.head(616)

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  Loan              Amount  \
0               5849                0.0                       NaN   
1               4583             1508.0                     128.0   
2               3000                0.0                      66.0   
3               2583             2358.0                     120.0   
4               6000                0.0                     141.0   
..               ...                ...                       ...   
609             2900                0.0                      71.0   
610             4106                0.0                      40.0   
611             8072              240.0                     253.0   
612             7583                0.0                     187.0   
613             4583                0.0                     133.0   

     Loan_Amount_Term  Credit_History Property_Area Loan_Status  
0               360.0             1.0         Urban           Y  
1               360.0             1.0         Rural           N  
2               360.0             1.0         Urban           Y  
3               360.0             1.0         Urban           Y  
4               360.0             1.0         Urban           Y  
..                ...             ...           ...         ...  
609             360.0             1.0         Rural           Y  
610             180.0             1.0         Rural           Y  
611             360.0             1.0         Urban           Y  
612             360.0             1.0         Urban           Y  
613             360.0             0.0     Semiurban           N  

[614 rows x 13 columns]

In [8]:
#find the row and column
print(data.shape)

(614, 13)


In [9]:
data.shape

(614, 13)

In [10]:
print('No of Row=',data.shape[0])
print('No of Columns=',data.shape[1])

No of Row= 614
No of Columns= 13


In [11]:
#loan Id count only show on true / drop:- Remove
data.Loan_ID.value_counts(dropna=False)

LP001002    1
LP002328    1
LP002305    1
LP002308    1
LP002314    1
           ..
LP001692    1
LP001693    1
LP001698    1
LP001699    1
LP002990    1
Name: Loan_ID, Length: 614, dtype: int64

In [12]:
#Gender
data.Gender.value_counts(dropna=False)

Male           482
Female         110
NaN             13
Transgender      9
Name: Gender, dtype: int64

In [13]:
#count Percentage of Male and female applicant
countMale = len(data[data.Gender == 'Male'])
countFemale = len(data[data.Gender == 'Female'])
countTransgender=len(data[data.Gender== 'Transgender'])
countNull = len(data[data.Gender.isnull()])

print("Percentage of Male applicant: {:.2f}%".format((countMale / (len(data.Gender))*100)))
print("Percentage of Female applicant: {:.2f}%".format((countFemale / (len(data.Gender))*100)))
print("Percentage of Transgender applicant: {:.2f}%".format((countTransgender/(len(data.Gender))*100)))
print("Missing values percentage: {:.2f}%".format((countNull / (len(data.Gender))*100)))

Percentage of Male applicant: 78.50%
Percentage of Female applicant: 17.92%
Percentage of Transgender applicant: 1.47%
Missing values percentage: 2.12%


In [14]:
#Married
data.Married.value_counts(dropna=False)

Yes    398
No     213
NaN      3
Name: Married, dtype: int64

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Loan_ID                   614 non-null    object 
 1   Gender                    601 non-null    object 
 2   Married                   611 non-null    object 
 3   Dependents                599 non-null    object 
 4   Education                 614 non-null    object 
 5   Self_Employed             582 non-null    object 
 6   ApplicantIncome           614 non-null    int64  
 7   CoapplicantIncome         614 non-null    float64
 8   Loan              Amount  592 non-null    float64
 9   Loan_Amount_Term          600 non-null    float64
 10  Credit_History            564 non-null    float64
 11  Property_Area             614 non-null    object 
 12  Loan_Status               614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 43.2+ KB


In [16]:
#Handling the Missing Value

In [17]:
data.isnull()

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0      False   False    False       False      False          False   
1      False   False    False       False      False          False   
2      False   False    False       False      False          False   
3      False   False    False       False      False          False   
4      False   False    False       False      False          False   
..       ...     ...      ...         ...        ...            ...   
609    False   False    False       False      False          False   
610    False   False    False       False      False          False   
611    False   False    False       False      False          False   
612    False   False    False       False      False          False   
613    False   False    False       False      False          False   

     ApplicantIncome  CoapplicantIncome  Loan              Amount  \
0              False              False                      True   
1              False              False                     False   
2              False              False                     False   
3              False              False                     False   
4              False              False                     False   
..               ...                ...                       ...   
609            False              False                     False   
610            False              False                     False   
611            False              False                     False   
612            False              False                     False   
613            False              False                     False   

     Loan_Amount_Term  Credit_History  Property_Area  Loan_Status  
0               False           False          False        False  
1               False           False          False        False  
2               False           False          False        False  
3               False           False          False        False  
4               False           False          False        False  
..                ...             ...            ...          ...  
609             False           False          False        False  
610             False           False          False        False  
611             False           False          False        False  
612             False           False          False        False  
613             False           False          False        False  

[614 rows x 13 columns]

In [18]:
data=data.drop('Loan_ID',axis=1)

In [19]:
data.head(1)

Gender Married Dependents Education Self_Employed  ApplicantIncome  \
0   Male      No          0  Graduate            No             5849   

   CoapplicantIncome  Loan              Amount  Loan_Amount_Term  \
0                0.0                       NaN             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y

In [20]:
#Count and sum of null value 
data.isnull().sum()

Gender                      13
Married                      3
Dependents                  15
Education                    0
Self_Employed               32
ApplicantIncome              0
CoapplicantIncome            0
Loan              Amount    22
Loan_Amount_Term            14
Credit_History              50
Property_Area                0
Loan_Status                  0
dtype: int64

In [21]:
#find percentage of sum of null value of Total value

In [22]:
data.isnull().sum()*100 / len(data)

Gender                      2.117264
Married                     0.488599
Dependents                  2.442997
Education                   0.000000
Self_Employed               5.211726
ApplicantIncome             0.000000
CoapplicantIncome           0.000000
Loan              Amount    3.583062
Loan_Amount_Term            2.280130
Credit_History              8.143322
Property_Area               0.000000
Loan_Status                 0.000000
dtype: float64

In [23]:
#Highest Null value of Percentage is Credit_History->8.14
#if 70% training data:-consider on Self_Employed--> 5.21
#Remove null value is less than 5.21 all columns

In [24]:
columns=['Gender','Dependents','Loan              Amount','Loan_Amount_Term']

In [25]:
data= data.dropna(subset=columns)

In [26]:
data.isnull().sum()*100/ len(data)

Gender                      0.000000
Married                     0.000000
Dependents                  0.000000
Education                   0.000000
Self_Employed               5.424955
ApplicantIncome             0.000000
CoapplicantIncome           0.000000
Loan              Amount    0.000000
Loan_Amount_Term            0.000000
Credit_History              8.679928
Property_Area               0.000000
Loan_Status                 0.000000
dtype: float64

In [27]:
#Remove null value:-Gender,Dependents,LoanAmount,Loan_Amount_Term

In [28]:
data['Self_Employed'].mode()[0]

'No'

In [29]:
data['Self_Employed']=data['Self_Employed'].fillna(data['Self_Employed'].mode()[0])

In [30]:
#Self Employee of removed null value:- 30% Testing data [Self Employed]

In [31]:
data.isnull().sum()*100/ len(data)


Gender                      0.000000
Married                     0.000000
Dependents                  0.000000
Education                   0.000000
Self_Employed               0.000000
ApplicantIncome             0.000000
CoapplicantIncome           0.000000
Loan              Amount    0.000000
Loan_Amount_Term            0.000000
Credit_History              8.679928
Property_Area               0.000000
Loan_Status                 0.000000
dtype: float64

In [32]:
#check on unique value as Self_Employed and Credit_History


In [33]:
data['Self_Employed'].unique()

array(['No', 'Yes'], dtype=object)

In [34]:
data['Credit_History'].unique()

array([ 1.,  0., nan])

In [35]:
data['Credit_History']=data['Credit_History'].fillna(data['Credit_History'].mode()[0])

In [36]:
data.isnull().sum()*100/ len(data)

Gender                      0.0
Married                     0.0
Dependents                  0.0
Education                   0.0
Self_Employed               0.0
ApplicantIncome             0.0
CoapplicantIncome           0.0
Loan              Amount    0.0
Loan_Amount_Term            0.0
Credit_History              0.0
Property_Area               0.0
Loan_Status                 0.0
dtype: float64

In [37]:
#successfully handling the Missing Value

In [38]:
#start- HandlingCategorical Columns

In [39]:
data.sample(6)

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
345    Male     Yes          0      Graduate            No             2499   
405  Female      No          0      Graduate            No             4547   
429    Male      No          0  Not Graduate            No             2717   
312  Female      No          0      Graduate            No             2507   
266    Male     Yes          2      Graduate            No             4708   
9      Male     Yes          1      Graduate            No            12841   

     CoapplicantIncome  Loan              Amount  Loan_Amount_Term  \
345             2458.0                     160.0             360.0   
405                0.0                     115.0             360.0   
429                0.0                      60.0             180.0   
312                0.0                      56.0             360.0   
266             1387.0                     150.0             360.0   
9              10968.0                     349.0             360.0   

     Credit_History Property_Area Loan_Status  
345             1.0     Semiurban           Y  
405             1.0     Semiurban           Y  
429             1.0         Urban           Y  
312             1.0         Rural           Y  
266             1.0     Semiurban           Y  
9               1.0     Semiurban           N

In [40]:
data['Dependents']=data['Dependents'].replace(to_replace="3+",value='4')

In [41]:
data['Dependents'].unique() #Check unique value

array(['1', '0', '2', '4'], dtype=object)

In [42]:
data['Gender'].unique()

array(['Male', 'Transgender', 'Female'], dtype=object)

In [43]:
data['Married'].unique()

array(['Yes', 'No'], dtype=object)

In [44]:
data['Education'].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [45]:
data['Property_Area'].unique()

array(['Rural', 'Urban', 'Semiurban'], dtype=object)

In [46]:
data['Self_Employed'].unique()

array(['No', 'Yes'], dtype=object)

In [47]:
data['Loan_Status'].unique()

array(['N', 'Y'], dtype=object)

In [48]:
obj =(data.dtypes =='object')
print("Categorical variables:",len(list(obj[obj].index)))


Categorical variables: 7


In [49]:
#Handling the Numerical Data

In [50]:
data['Gender'] = data['Gender'].map({'Male':1,'Transgender':2,'Female':0}).astype('int')

In [51]:
data['Gender'].unique()

array([1, 2, 0])

In [52]:
data['Married']=data['Married'].map({'Yes':1, 'No':0}).astype('int')

In [53]:
data['Married'].unique()

array([1, 0])

In [54]:
data['Education']=data['Education'].map({'Graduate':1, 'Not Graduate':0}).astype('int')

In [55]:
data['Education'].unique()

array([1, 0])

In [56]:
data['Self_Employed']=data['Self_Employed'].map({'No':0, 'Yes':1}).astype('int')

In [57]:
data['Self_Employed'].unique()

array([0, 1])

In [58]:
data['Property_Area']=data['Property_Area'].map({'Rural':0, 'Urban':1, 'Semiurban':2}).astype('int')

In [59]:
data['Property_Area'].unique()

array([0, 1, 2])

In [60]:
data['Loan_Status']=data['Loan_Status'].map({'N':0, 'Y':1}).astype('int')

In [61]:
data['Loan_Status'].unique()

array([0, 1])

In [62]:
data.head(10)

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
1        1        1          1          1              0             4583   
2        1        1          0          1              1             3000   
3        1        1          0          0              0             2583   
4        1        0          0          1              0             6000   
5        2        1          2          1              1             5417   
6        1        1          0          0              0             2333   
7        1        1          4          1              0             3036   
8        1        1          2          1              0             4006   
9        1        1          1          1              0            12841   
10       1        1          2          1              0             3200   

    CoapplicantIncome  Loan              Amount  Loan_Amount_Term  \
1              1508.0                     128.0             360.0   
2                 0.0                      66.0             360.0   
3              2358.0                     120.0             360.0   
4                 0.0                     141.0             360.0   
5              4196.0                     267.0             360.0   
6              1516.0                      95.0             360.0   
7              2504.0                     158.0             360.0   
8              1526.0                     168.0             360.0   
9             10968.0                     349.0             360.0   
10              700.0                      70.0             360.0   

    Credit_History  Property_Area  Loan_Status  
1              1.0              0            0  
2              1.0              1            1  
3              1.0              1            1  
4              1.0              1            1  
5              1.0              1            1  
6              1.0              1            1  
7              0.0              2            0  
8              1.0              1            1  
9              1.0              2            0  
10             1.0              1            1

In [65]:
#Store feature matrix in X and Response (Target)in vector Y


In [66]:
X=data.drop('Loan_Status',axis=1)

In [67]:
y=data['Loan_Status']

In [68]:
y

1      0
2      1
3      1
4      1
5      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 553, dtype: int32

In [69]:
data.head()

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
1       1        1          1          1              0             4583   
2       1        1          0          1              1             3000   
3       1        1          0          0              0             2583   
4       1        0          0          1              0             6000   
5       2        1          2          1              1             5417   

   CoapplicantIncome  Loan              Amount  Loan_Amount_Term  \
1             1508.0                     128.0             360.0   
2                0.0                      66.0             360.0   
3             2358.0                     120.0             360.0   
4                0.0                     141.0             360.0   
5             4196.0                     267.0             360.0   

   Credit_History  Property_Area  Loan_Status  
1             1.0              0            0  
2             1.0              1            1  
3             1.0              1            1  
4             1.0              1            1  
5             1.0              1            1

In [95]:
#Feature scaling

In [96]:
columns=['ApplicantIncome','CoapplicantIncome','Loan              Amount','Loan_Amount_Term']

In [97]:
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
X[columns]=st.fit_transform(X[columns])


In [98]:
X

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
1         1        1          1          1              0        -0.128694   
2         1        1          0          1              1        -0.394296   
3         1        1          0          0              0        -0.464262   
4         1        0          0          1              0         0.109057   
5         2        1          2          1              1         0.011239   
..      ...      ...        ...        ...            ...              ...   
609       0        0          0          1              0        -0.411075   
610       1        1          4          1              0        -0.208727   
611       1        1          1          1              0         0.456706   
612       1        1          2          1              0         0.374659   
613       0        0          0          1              1        -0.128694   

     CoapplicantIncome  Loan              Amount  Loan_Amount_Term  \
1            -0.049699                 -0.214368          0.279961   
2            -0.545638                 -0.952675          0.279961   
3             0.229842                 -0.309634          0.279961   
4            -0.545638                 -0.059562          0.279961   
5             0.834309                  1.440866          0.279961   
..                 ...                       ...               ...   
609          -0.545638                 -0.893134          0.279961   
610          -0.545638                 -1.262287         -2.468292   
611          -0.466709                  1.274152          0.279961   
612          -0.545638                  0.488213          0.279961   
613          -0.545638                 -0.154828          0.279961   

     Credit_History  Property_Area  
1               1.0              0  
2               1.0              1  
3               1.0              1  
4               1.0              1  
5               1.0              1  
..              ...            ...  
609             1.0              0  
610             1.0              0  
611             1.0              1  
612             1.0              1  
613             0.0              2  

[553 rows x 11 columns]

In [110]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
# from sklearn.metrices import accuracy_score